# MOTIVATION
# ----------
# changes a given user's password for the
# machines listed in the inventory file
#
# EXAMPLE
# -------
# ansible-playbook \
#   -u someuserwithprivileges \
#   --inventory hosts.init \
#   --key-file="~/.ssh/id_rsa" \
#   change-password.yml
---
- hosts: all
  vars_prompt:
    - name: username
      prompt: which user name you want to change the password for ?
      private: no
    - name: new_password
      prompt: new password ?
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
      private: yes
  become: true
  tasks:
    - name: Change password
      user:
        name: "{{ username }}"
        password: "{{ new_password }}"
