---
- hosts: all
  vars_prompt:

    - name: netmask
      prompt: What is the netmask u wanna use ?
      default: 255.255.255.0
      private: no
    - name: gateway
      prompt: What is the gateway u wanna use ?
      default: 192.168.1.1
      private: no
  roles:
    - static-ip
  become: true
