---
- hosts: all
  vars_prompt:
    - name: username
      prompt: "Insert the username"
      private: no

    - name: password
      prompt: "Insert the password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7

    - name: public_key_path
      prompt: "Where is the public key ?"
      private: no
  roles:
    - usr-add
  become: true
