- name: nfs libraries [common]
  apt:
    name: ['curl', 'nfs-common', 'nfs-kernel-server']
    state: present

- name: create shared directories [client]
  file:
    path: "/var/nfs"
    state: directory
    owner: nobody
    group: nogroup
    mode: 755
    creates: /var/nfs
  when: nfs_role == "client"

- name: mount nfs [client]
  mount:
    src: "{{ nfs_server_ip }}:/var/nfs"
    path: "/var/nfs"
    fstype: nfs
    opts: defaults,rw,bg
    state: mounted
    creates: /var/nfs
  when: nfs_role == "client"

- name: create shared directories [server]
  file:
    path: "/var/nfs"
    state: directory
    owner: nobody
    group: nogroup
    mode: u=rw,g=rw,o=rw
  when: nfs_role == "server"

- name: copy /etc/exports [server]
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
  when: nfs_role == "server"

- name: restart nfs server [server]
  service:
    name: nfs-kernel-server
    state: restarted
  when: nfs_role == "server"
