- name: Operations user
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
    shell: /bin/bash
    groups:
      - sudo
      - vagrant
      - cdrom
      - floppy
      - audio
      - dip
      - video
      - plugdev
      - netdev

- name: Set authorized key took from file
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', public_key_path) }}"
